fileVersion: 1
id: "3"
mappingDefinitions:
  USG_MASTER:
    database: ""
    schema: ""
  USG_RAW_EPA:
    database: ""
    schema: ""
  USG_RAW_HUBSPOT:
    database: USG_RAW
    schema: HUBSPOT_HUBSPOT
  USG_RAW_HUBSPOT_RAW:
    database: ""
    schema: ""
  USG_RAW_MAPPING:
    database: ""
    schema: ""
  USG_RAW_ORACLE_ANALYTICSSERVICE:
    database: USG_RAW
    schema: ORACLE_FUSION_CLOUD_APPS_CRM_ANALYTICSSERVICE
  USG_RAW_ORACLE_EBS:
    database: USG_RAW
    schema: ORACLE_MANUAL_LOAD
  USG_RAW_ORACLE_SC_ACTIVITIES:
    database: USG_RAW
    schema: ORACLE_FUSION_CLOUD_APPS_CRM_ACTIVITIES
  USG_RAW_ORACLE_SC_HZBICCEXTRACT:
    database: USG_RAW
    schema: ORACLE_FUSION_CLOUD_APPS_CRM_CRMEXTRACT_HZBICCEXTRACT
  USG_RAW_ORACLE_SC_LEADS:
    database: USG_RAW
    schema: ORACLE_FUSION_CLOUD_APPS_CRM_LEAD
  USG_RAW_ORACLE_SC_MKLBICCEXTRACT:
    database: ""
    schema: ""
  USG_RAW_ORACLE_SC_MOOBICCEXTRACT:
    database: ""
    schema: ""
  USG_RAW_ORACLE_SC_OPPORTUNITY:
    database: USG_RAW
    schema: ORACLE_FUSION_CLOUD_APPS_CRM_OPPORTUNITY
  USG_RAW_ORACLE_SC_PARTIESANALYTICS:
    database: USG_RAW
    schema: ORACLE_FUSION_CLOUD_APPS_CRM_PARTIESANALYTICS
  USG_RAW_ORACLE_SC_PERSON:
    database: USG_RAW
    schema: ORACLE_FUSION_CLOUD_APPS_CRM_PERSON
  USG_RAW_ORACLE_SC_SALESPARTY:
    database: USG_RAW
    schema: ORACLE_FUSION_CLOUD_APPS_CRM_SALESPARTY
  USG_RAW_ORACLE_SC_TERRITORY:
    database: USG_RAW
    schema: ORACLE_FUSION_CLOUD_APPS_CRM_TERRITORY
  USG_RAW_SQL_SERVER:
    database: USG_RAW
    schema: SQL_SERVER_DBO
  USG_STG_EPA:
    database: ""
    schema: ""
  USG_STG_HUBSPOT:
    database: ""
    schema: ""
  USG_STG_MASTER:
    database: ""
    schema: ""
  USG_STG_ORACLE_EBS:
    database: USG_PROD
    schema: STG_ORACLE_EBS
  USG_STG_ORACLE_SALES_CLOUD:
    database: USG_PROD
    schema: STG_ORACLE_SALES_CLOUD
  USG_STG_SQL_SERVER:
    database: USG_PROD
    schema: STG_SQL_SERVER
  WORK:
    database: USG_RAW
    schema: HUBSPOT
name: Production
type: Environment
