fileVersion: 1
id: "3"
mappingDefinitions:
  USG_MASTER:
    database: USG_PROD
    schema: MASTER
  USG_RAW_EBS_BOLINF:
    database: USG_RAW
    schema: ORACLE_EBS_BOLINF
  USG_RAW_EBS_JTF:
    database: USG_RAW
    schema: ORACLE_EBS_JTF
  USG_RAW_EBS_ONT:
    database: USG_RAW
    schema: ORACLE_EBS_ONT
  USG_RAW_EBS_PA:
    database: USG_RAW
    schema: ORACLE_EBS_PA
  USG_RAW_EBS_XXLAAPPS:
    database: USG_RAW
    schema: ORACLE_EBS_XXLAAPPS
  USG_RAW_EPA:
    database: USG_RAW
    schema: EPA_DATA_RAW
  USG_RAW_HUBSPOT:
    database: USG_RAW
    schema: HUBSPOT_HUBSPOT
  USG_RAW_HUBSPOT_RAW:
    database: USG_RAW
    schema: HUBSPOT
  USG_RAW_MAPPING:
    database: USG_RAW
    schema: MAPPING
  USG_RAW_ORACLE_ANALYTICSSERVICE:
    database: USG_RAW
    schema: ORACLE_FUSION_CLOUD_APPS_CRM_ANALYTICSSERVICE
  USG_RAW_ORACLE_EBS:
    database: USG_RAW
    schema: ORACLE_MANUAL_LOAD
  USG_RAW_ORACLE_EBS_APPS:
    database: USG_RAW
    schema: ORACLE_EBS_APPS
  USG_RAW_ORACLE_EBS_AR:
    database: USG_RAW
    schema: ORACLE_EBS_AR
  USG_RAW_ORACLE_EBS_CUSTOM:
    database: USG_RAW
    schema: ORACLE_EBS_USG_CUSTOM
  USG_RAW_ORACLE_EBS_GL:
    database: USG_RAW
    schema: ORACLE_EBS_GL
  USG_RAW_ORACLE_SC_ACTIVITIES:
    database: USG_RAW
    schema: ORACLE_FUSION_CLOUD_APPS_CRM_ACTIVITIES
  USG_RAW_ORACLE_SC_HZBICCEXTRACT:
    database: USG_RAW
    schema: ORACLE_FUSION_CLOUD_APPS_CRM_CRMEXTRACT_HZBICCEXTRACT
  USG_RAW_ORACLE_SC_LEADS:
    database: USG_RAW
    schema: ORACLE_FUSION_CLOUD_APPS_CRM_LEAD
  USG_RAW_ORACLE_SC_MKLBICCEXTRACT:
    database: USG_RAW
    schema: ORACLE_FUSION_CLOUD_APPS_CRM_CRMEXTRACT_MKLBICCEXTRACT
  USG_RAW_ORACLE_SC_MOOBICCEXTRACT:
    database: USG_RAW
    schema: ORACLE_FUSION_CLOUD_APPS_CRM_CRMEXTRACT_MOOBICCEXTRACT
  USG_RAW_ORACLE_SC_OPPORTUNITY:
    database: USG_RAW
    schema: ORACLE_FUSION_CLOUD_APPS_CRM_OPPORTUNITY
  USG_RAW_ORACLE_SC_PARTIESANALYTICS:
    database: USG_RAW
    schema: ORACLE_FUSION_CLOUD_APPS_CRM_PARTIESANALYTICS
  USG_RAW_ORACLE_SC_PERSON:
    database: USG_RAW
    schema: ORACLE_FUSION_CLOUD_APPS_CRM_PERSON
  USG_RAW_ORACLE_SC_SALESPARTY:
    database: USG_RAW
    schema: ORACLE_FUSION_CLOUD_APPS_CRM_SALESPARTY
  USG_RAW_ORACLE_SC_TERRITORY:
    database: USG_RAW
    schema: ORACLE_FUSION_CLOUD_APPS_CRM_TERRITORY
  USG_RAW_SHARE_POINT_MAPPING_FILES:
    database: USG_RAW
    schema: SHARE_POINT_MAPPING_FILES
  USG_RAW_SHARE_POINT_TAI_DATA:
    database: USG_RAW
    schema: SHARE_POINT_TAI_DATA
  USG_RAW_SQL_SERVER:
    database: USG_RAW
    schema: SQL_SERVER_DBO
  USG_STG_EPA:
    database: USG_PROD
    schema: STG_EPA
  USG_STG_HUBSPOT:
    database: USG_PROD
    schema: STG_HUBSPOT
  USG_STG_MASTER:
    database: USG_PROD
    schema: STG_MASTER
  USG_STG_ORACLE_EBS:
    database: USG_PROD
    schema: STG_ORACLE_EBS
  USG_STG_ORACLE_SALES_CLOUD:
    database: USG_PROD
    schema: STG_ORACLE_SALES_CLOUD
  USG_STG_SHAREPOINT:
    database: USG_PROD
    schema: STG_SHAREPOINT
  USG_STG_SQL_SERVER:
    database: USG_PROD
    schema: STG_SQL_SERVER
name: Production
type: Environment
